# module name, required
name: ${oc.env:MODULE_NAME, 'telemetry-demo'}

# base module parameters
parameters:
  batch_size: 1

# pipeline definition
pipeline:
  elements:
    # simple pyfunc blurring frames
    - element: pyfunc
      module: samples.key_value_api.counter
      class_name: Counter
